using System.Net.Http;

namespace OnaPlotter.Services;

/// <summary>
/// Polls the static <c>js/version.g.js</c> on the server every
/// <see cref="CheckIntervalMinutes"/> minutes. When the published
/// build hash differs from <see cref="OnaPlotter.BuildInfo.CommitHash"/>
/// (the hash baked into THIS WASM bundle at compile time), flips
/// <see cref="IsUpdateAvailable"/> and fires
/// <see cref="OnChanged"/> so the UI can surface a "Reload to
/// update" chip.
/// <para>
/// Why poll the JS file rather than <c>_framework/blazor.boot.json</c>:
/// version.g.js is tiny (one assignment line, ~80 bytes), regenerated
/// by the StampBuildInfo MSBuild target on every build, and already
/// served as a regular static asset by the SignalK webapp host.
/// blazor.boot.json carries hashes for every WASM file but a fetch
/// + parse on each tick would dwarf the version.g.js fetch in cost.
/// </para>
/// </summary>
public sealed class UpdateChecker : IDisposable
{
    /// <summary>How often to re-fetch <c>version.g.js</c>. 5 minutes
    /// balances "helm gets a Reload prompt within an acceptable
    /// window of a deploy" against "we're not hammering the server
    /// when the helm leaves the page open all weekend". The first
    /// check fires <see cref="FirstCheckSeconds"/> seconds after
    /// startup so a freshly-loaded page that's already on the
    /// latest hash doesn't waste a sync HTTP round-trip during
    /// the warm-up.</summary>
    public const int CheckIntervalMinutes = 5;
    public const int FirstCheckSeconds = 30;

    private readonly HttpClient _http;
    private readonly System.Threading.Timer _timer;
    private readonly string _embeddedHash = OnaPlotter.BuildInfo.CommitHash;
    private bool _disposed;

    /// <summary>Latest hash observed on the server. Null until the
    /// first poll resolves; thereafter the most-recently-fetched
    /// value (UPDATE checks may legitimately roll the hash backward
    /// during a rollback, in which case we still surface a Reload
    /// chip so the helm picks up the rollback as well).</summary>
    public string? LatestHash { get; private set; }

    /// <summary>True when the server's hash differs from the bundle
    /// the helm is currently running. Sticky once flipped: even if a
    /// later poll happens to match again (eg. multi-server load
    /// balancer with stale node), the helm has already SEEN the
    /// new-bundle prompt, so we don't take it back.</summary>
    public bool IsUpdateAvailable { get; private set; }

    /// <summary>Fires whenever <see cref="IsUpdateAvailable"/> or
    /// <see cref="LatestHash"/> changes. UI components subscribe to
    /// re-render the chip.</summary>
    public event Action? OnChanged;

    public UpdateChecker(HttpClient http)
    {
        _http = http;
        _timer = new System.Threading.Timer(
            _ => _ = CheckAsync(),
            state: null,
            dueTime: TimeSpan.FromSeconds(FirstCheckSeconds),
            period: TimeSpan.FromMinutes(CheckIntervalMinutes));
    }

    /// <summary>Manual trigger - used by tests + the "check now"
    /// path if we ever surface one. Same hash-extract parser as the
    /// timer path; safe to call concurrently (the timer's tick is
    /// also fire-and-forget so a manual call interleaving with the
    /// timer just produces two parallel requests, which is harmless).</summary>
    public async Task CheckAsync()
    {
        if (_disposed) return;
        try
        {
            // Cache-buster query param. Browser caches version.g.js
            // unless told otherwise, and a stale cache would defeat
            // the whole check. ?_=ticks is opaque to the server but
            // fingerprints the URL so the browser refetches.
            var url = $"js/version.g.js?_={DateTime.UtcNow.Ticks}";
            var content = await _http.GetStringAsync(url);
            var serverHash = TryParseHash(content);
            if (serverHash is null) return; // malformed payload; try again next tick
            if (serverHash == LatestHash && LatestHash is not null) return;
            LatestHash = serverHash;
            // Flip the latch only when the embedded hash is known
            // (a "?" / "unknown" build means we can't compare). The
            // StampBuildInfo target falls back to "unknown" only on
            // a CI machine without git; on a real build the hash is
            // always set.
            if (!string.IsNullOrEmpty(_embeddedHash)
                && _embeddedHash != "unknown"
                && serverHash != _embeddedHash)
            {
                IsUpdateAvailable = true;
            }
            OnChanged?.Invoke();
        }
        catch (HttpRequestException) { /* offline / 404; retry next tick */ }
        catch (TaskCanceledException) { /* timeout; retry */ }
    }

    /// <summary>
    /// Extracts the build hash from a <c>version.g.js</c> payload.
    /// The file is generated by the <c>StampBuildInfo</c> MSBuild
    /// target with a fixed shape:
    /// <code>window.OnaPlotterBuild = { hash: "abc1234", utc: "..." };</code>
    /// We pull the value between the first pair of double quotes
    /// after <c>hash:</c>. Returns null on any malformed payload
    /// (truncated download, server rewrote the file, content-type
    /// mismatch); the caller treats that as "try again next tick".
    /// <para>
    /// Hand-rolled scan instead of <c>System.Text.RegularExpressions</c>:
    /// the single Regex call here was the only consumer of that
    /// assembly across the entire app, and replacing it lets the
    /// trimmer drop ~71 KB brotli of regex engine from the bundle.
    /// </para>
    /// </summary>
    internal static string? TryParseHash(string content)
    {
        if (string.IsNullOrEmpty(content)) return null;
        // Find the "hash:" key. Ordinal compare keeps culture data out
        // of the trim graph; the file is ASCII-only by construction.
        const string anchor = "hash:";
        int anchorEnd = content.IndexOf(anchor, StringComparison.Ordinal);
        if (anchorEnd < 0) return null;
        anchorEnd += anchor.Length;

        // First double quote after the anchor.
        int firstQuote = content.IndexOf('"', anchorEnd);
        if (firstQuote < 0) return null;
        int valueStart = firstQuote + 1;

        // Closing quote.
        int secondQuote = content.IndexOf('"', valueStart);
        if (secondQuote < 0) return null;

        // Empty value -> "no hash" rather than ""; lets the caller
        // treat this the same as a malformed payload.
        return secondQuote == valueStart
            ? null
            : content.Substring(valueStart, secondQuote - valueStart);
    }

    public void Dispose()
    {
        _disposed = true;
        _timer.Dispose();
    }
}
