using OnaPlotter.Services;

namespace OnaPlotter.Tests;

/// <summary>
/// Pins the <see cref="UpdateChecker.TryParseHash"/> contract.
/// Replaced an earlier <c>Regex.Match</c> call so the bundle could
/// drop the System.Text.RegularExpressions dependency entirely
/// (~71 KB brotli, the assembly's only caller in the app).
/// The behaviour-equivalence cases below cover the hashes the old
/// regex would have matched, plus the malformed-input degradations.
/// </summary>
public class UpdateCheckerParseTests
{
    [Test]
    public async Task Canonical_VersionJs_Returns_The_Hash()
    {
        // Exact shape the StampBuildInfo MSBuild target writes.
        const string payload =
            "// <auto-generated /> written by StampBuildInfo target.\n" +
            "window.OnaPlotterBuild = { hash: \"abc1234\", utc: \"2026-04-24 12:34\" };";
        await Assert.That(UpdateChecker.TryParseHash(payload)).IsEqualTo("abc1234");
    }

    [Test]
    public async Task Compact_NoSpace_After_Colon()
    {
        // Older / hand-edited variants might omit the space; the
        // earlier regex used \s* so it was tolerant. Match that.
        await Assert.That(UpdateChecker.TryParseHash("hash:\"deadbeef\""))
            .IsEqualTo("deadbeef");
    }

    [Test]
    public async Task Multiple_Whitespace_Tolerated()
    {
        // Tabs / newlines between key and value: still parses.
        await Assert.That(UpdateChecker.TryParseHash("hash:\t \"feedface\""))
            .IsEqualTo("feedface");
    }

    [Test]
    public async Task Empty_String_Returns_Null()
    {
        await Assert.That(UpdateChecker.TryParseHash("")).IsNull();
    }

    [Test]
    public async Task Null_Returns_Null()
    {
        await Assert.That(UpdateChecker.TryParseHash(null!)).IsNull();
    }

    [Test]
    public async Task Missing_Anchor_Returns_Null()
    {
        // Server returned an HTML error page or unrelated JSON.
        await Assert.That(UpdateChecker.TryParseHash("<html>404</html>")).IsNull();
        await Assert.That(UpdateChecker.TryParseHash("{\"name\":\"foo\"}")).IsNull();
    }

    [Test]
    public async Task Anchor_Without_Quoted_Value_Returns_Null()
    {
        // Truncated file: anchor found, but no closing quote pair.
        await Assert.That(UpdateChecker.TryParseHash("hash:")).IsNull();
        await Assert.That(UpdateChecker.TryParseHash("hash: ")).IsNull();
        await Assert.That(UpdateChecker.TryParseHash("hash: \"unterminated")).IsNull();
    }

    [Test]
    public async Task Empty_Quoted_Value_Returns_Null()
    {
        // hash: "" is not a valid build hash; treat as "no hash" so
        // the caller's "?" / "unknown" guard fires correctly rather
        // than latching IsUpdateAvailable on every poll.
        await Assert.That(UpdateChecker.TryParseHash("hash: \"\"")).IsNull();
    }

    [Test]
    public async Task First_Hash_Wins_When_File_Has_Multiple()
    {
        // Defensive: if a future build artefact accidentally embeds
        // two `hash:` keys, the first-wins behaviour matches both
        // the old regex (which returned the first match) and the
        // new IndexOf-based scan.
        const string payload = "{ hash: \"first1\", other: { hash: \"second2\" } }";
        await Assert.That(UpdateChecker.TryParseHash(payload)).IsEqualTo("first1");
    }
}
